-- Dummy Data --
INSERT INTO dummy (created) VALUES (current_timestamp);
-- Populate Your Tables Here --
DELETE FROM listing;
INSERT INTO listing(category,listing) VALUES ('vehicles', '{"name": "Elrim", "title": "2002 Toyota Tacamo", "price": "200", "location": "Los Angeles, CA", "date": "August 7,2020", "imgList": ["https://static.cargurus.com/images/site/2008/01/04/01/51/2002_toyota_tacoma_2_dr_v6_4wd_extended_cab_sb-pic-45759-1600x1200.jpeg"]}');
INSERT INTO listing(category,listing) VALUES ('boats', '{"name": "Heimlic", "title": "Vintage Boat",  "price": "200", "location": "Santa Cruz, CA", "date": "August 7,2020", "imgList": ["https://www.greatlakesboatsandbrokerage.com/wp/wp-content/uploads/greatlakesboatsandbrokerage.com/2018/11/carousel-55.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('boats', '{"name": "Heimlic", "title": " Boat", "price": "200", "location": "Santa Fe, CA", "date": "June 7,2020", "imgList": ["http://southeastexsports.com/galleries/origin/19weldcraft1860bass4.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('toys', '{"name": "Bonzi", "title": "Pokemon Cards", "price": "200","location": "Boston, NY", "date": "August 7,2020", "imgList": ["https://images.saymedia-content.com/.image/t_share/MTc5ODE2MjE2Mjc2NDQ0Nzgz/best-v-pokemon-cards.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('toys', '{"name": "Banonzai", "title": "Rare Pokemon Cards", "price": "200", "location": "San Francisco, CA","date": "August 7,2019", "imgList": ["https://m.media-amazon.com/images/I/71l8+QwwhrL._AC_SL1000_.jpg", "https://media.karousell.com/media/photos/products/2020/11/15/pokemon_cards_for_sale_2_1605418973_7e14e022.jpg", "https://img.5milesapp.com/image/upload/f_auto,t_i800/v1614502364/item/twtbueeim7uptryknel7.jpg", "https://pixl.varagesale.com/http://s3.amazonaws.com/hopshop-image-store-production/62829419/c209616f382b1ba0a48a6be0ed1a9017.jpg?_ver=large_uploader_thumbnail&w=640&h=640&fit=crop&s=3f701a766810bd9e9ce379660856f361"]}');
INSERT INTO listing(category,listing) VALUES ('toys', '{"name": "Bono", "title": "Garage Sale Toys", "price": "200","location": "San Jose, CA", "date": "August 7,2019", "imgList": ["https://media1.popsugar-assets.com/files/thumbor/76IVOu8kgWklKmSiBO4lzwBhdDM/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2012/06/25/1/192/1922664/9e84ecfdf4a8aebe_Toy_Box/i/Sort-Through-Old-Toys-Plan-Garage-Sale.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('shoes', '{"name": "The Shoe Plug", "title": "University Blue Jordan 1", "location": "Watsonville, CA", "price": "200", "date": "March 31,2020", "imgList": ["https://sneakernews.com/wp-content/uploads/2021/01/Air-Jordan-1-University-Blue-555088-134-2.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('shoes', '{"name": "The Shoe Plug", "title": "University Blue Jordan 1", "location": "Irvine, CA","price": "200", "date": "March 31,2020", "imgList": ["https://sneakernews.com/wp-content/uploads/2021/01/Air-Jordan-1-University-Blue-555088-134-2.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('shoes', '{"name": "The Shoe Plug", "title": "Air Jordan 4 - Fire Red", "location": "Riverside, CA", "price": "200", "date": "February 31,2019", "imgList": ["https://cdn.flightclub.com/TEMPLATE/178193/1.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('mens', '{"name": "Menlo Man", "title": "SB NIKE Hoodie",  "price": "200", "location": "Santa Barbara, CA", "date": "February 21,2019", "imgList": ["https://scene7.zumiez.com/is/image/zumiez/product_main_medium/Nike-SB-Icon-Black-and-White-Hoodie-_268236-front-US.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('mens', '{"name": "BreakBoi", "title": "Gorillaz Shirt", "price": "200", "location": "Berkeley, CA", "date": "February 31,2019", "imgList": ["https://teedodi.com/wp-content/uploads/2021/09/GORILLAZ-SHIRT.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('shoes', '{"name": "Epsonal Madre", "title": "Slippers", "price": "200", "location": "Stanford, CA", "date": "February 31,2019", "imgList": ["https://www.bigsalemax.com/wp-content/uploads/2018/04/Cheap-AD-Adilette-NeighBorhood-Boost-Black-White-S80769-Summer-Slippers-Sale.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('electronics', '{"name": "Manzo", "title": "Used Ipad", "price": "200","location": "Susville, CA","date": "June 18,2019", "imgList": ["https://storage.bhs.cloud.ovh.net/v1/AUTH_e7d15450bedd40b9b599e075527df3cb/tucson/fUnused_iPad_Pro__1TB_storage__silver_col_5d6710991cf98.jpg"]}');
INSERT INTO listing(category,listing) VALUES ('phones', '{"name": "Kedma", "title": "Iphone 11", "price": "200","location": "Menlo Park, CA", "date": "May 10,2019", "imgList": ["https://pixl.varagesale.com/http://s3.amazonaws.com/hopshop-image-store-production/184467333/c484e17adf011b58fa4953a09a381559.jpg?_ver=large&w=1500&h=1500&fit=max&s=419fec08382ec3850467d14f8ebca39c"]}');
-- Populate Category Table --
DELETE FROM category;
INSERT INTO category(categoryName, category) VALUES ('Vehicles', '{"sub":["Boats"],"filter":[{"name":"Sort by","type":"radio","value":["Recommended","Price: Lowest first","Price: Highest first","Date listed: Newest first","Date listed: Oldest first"]},{"name":"Price","type":"input"},{"name":"Vehicle type","type":"radio","value":["All","Boats","Motorcycles","Trailers"]},{"name":"Year","type":"input"},{"name":"Transmission type","type":"radio","value":["All","Automatic","Manual"]},{"name":"Mileage","type":"input"}]}');
INSERT INTO category(categoryName, category) VALUES ('Boats', '{"sub":[],"filter":[{"name":"Sort by","type":"radio","value":["Recommended","Price: Lowest first","Price: Highest first","Date listed: Newest first","Date listed: Oldest first"]},{"name":"Price","type":"input"},{"name":"Year","type":"input"}]}');
INSERT INTO category(categoryName, category) VALUES ('Apparel', '{"sub":["Mens","Shoes"],"filter":[{"name":"Price","type":"input"},{"name":"Delivery method","type":"radio","value":["All","Local Pickup","Shipping"]},{"name":"Item condition","type":"radio","value":["All","New","Used"]}]}');
INSERT INTO category(categoryName, category) VALUES ('Mens', '{"sub":[],"filter":[{"name":"Price","type":"input"},{"name":"Delivery method","type":"radio","value":["All","Local Pickup","Shipping"]},{"name":"Item condition","type":"radio","value":["All","New","Used"]}]}');
INSERT INTO category(categoryName, category) VALUES ('Shoes', '{"sub":[],"filter":[{"name":"Price","type":"input"},{"name":"Delivery method","type":"radio","value":["All","Local Pickup","Shipping"]},{"name":"Item condition","type":"radio","value":["All","New","Used"]},{"name":"Brand","type":"checkbox","value":["Nike","Adidas"]}]}');
INSERT INTO category(categoryName, category) VALUES ('Electronics', '{"sub":["Phones"],"filter":[{"name":"Price","type":"input"},{"name":"Delivery method","type":"radio","value":["All","Local Pickup","Shipping"]},{"name":"Item condition","type":"radio","value":["All","New","Used"]}]}');
INSERT INTO category(categoryName, category) VALUES ('Phones', '{"sub":[],"filter":[{"name":"Price","type":"input"},{"name":"Delivery method","type":"radio","value":["All","Local Pickup","Shipping"]},{"name":"Item condition","type":"radio","value":["All","New","Used"]},{"name":"Brand","type":"checkbox","value":["Apple","Google"]}]}');
INSERT INTO category(categoryName, category) VALUES ('Toys', '{"sub":[],"filter":[{"name":"Price","type":"input"},{"name":"Delivery method","type":"radio","value":["All","Local Pickup","Shipping"]},{"name":"Item condition","type":"radio","value":["All","New","Used"]}]}');
-- Populate user for testing --
DELETE FROM users;
INSERT INTO users(fn, ln, email, phone, password) VALUES ('Kevin', 'Wang', 'bwang93@ucsc.edu', '8888888888', '$2b$10$Y00XOZD/f5gBSpDusPUgU.iJufk6Nxx6gAoHRG8t2eHyGgoP2bK4y');
